[theme]
# Cor primária: Usada para botões, links, e destaques. 
primaryColor = "#FF5C5C" 

# Cor do fundo dos blocos de conteúdo 
secondaryBackgroundColor = "#F0F2F6" 

# Cor do texto
textColor = "#1E1E1E" 

# Tipo de fonte
font = "inter"

[browser]